Repository sassoftware/viya4-iac-k8s, pull requests merged in 2022-07, with the labels that each got.

#7 (IAC-592) kube-vip updates
  docs/CONFIG-VARS.md
  docs/REQUIREMENTS.md
  examples/vsphere/sample-terraform-minimal.tfvars
  examples/vsphere/sample-terraform-vi.tfvars
  examples/vsphere/sample-terraform.tfvars
  main.tf
  roles/kubernetes/loadbalancer/kube_vip/primary/tasks/main.yaml
  templates/ansible/ansible-vars.yaml.tmpl
  variables.tf
Labels: documentation, enhancement

#10 (IAC-605) Don't replace GRUB_CMDLINE_LINUX if it already exists
  roles/kubernetes/common/tasks/main.yaml
Labels: enhancement

#22 fix: (IAC-621) Update Ansible template files
  templates/ansible/ansible-vars.yaml.tmpl
  templates/ansible/inventory.tmpl
Labels: bug

#14 feat: (IAC-578) SSL Configuration Support for Postgres
  docs/CONFIG-VARS.md
  roles/systems/postgres/defaults/main.yaml
  roles/systems/postgres/tasks/main.yaml
  templates/ansible/inventory.tmpl
  variables.tf
Labels: documentation, enhancement

#23 (IAC-626) Updating DHCP items for local_storage
  README.md
  docs/user/DockerUsage.md
  modules/vm/main.tf
  roles/kubernetes/storage/sig-storage-local-static-provisioner/defaults/main.yaml
Labels: bug

#27 fix: (IAC-578) Update SSL Cert/Key Naming Scheme
  docs/CONFIG-VARS.md
  roles/systems/postgres/tasks/main.yaml
Labels: bug
