Repository sassoftware/viya4-iac-k8s, pull requests merged in 2023-06, with the labels that each got.

#73 fix: (IAC-1019) Use apt-get tool in Dockerfile per hadolint recommendation
  Dockerfile
Labels: bug

#75 feat: (IAC-1049) (IAC-1048) Add kubernetes_cri_version & cluster_cri_version variables and update uninstall task
  docs/CONFIG-VARS.md
  docs/REQUIREMENTS.md
  examples/bare-metal/sample-ansible-vars.yaml
  examples/vsphere/sample-terraform-dhcp.tfvars
  examples/vsphere/sample-terraform-minimal.tfvars
  examples/vsphere/sample-terraform-static-ips.tfvars
  examples/vsphere/sample-terraform-static-singlestore.tfvars
  examples/vsphere/sample-terraform-vi.tfvars
  main.tf
  roles/kubernetes/cri/containerd/defaults/main.yaml
  roles/kubernetes/cri/containerd/tasks/main.yaml
  templates/ansible/ansible-vars.yaml.tmpl
  variables.tf
Labels: enhancement

#79 3.2.0 - June 26, 2023
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  docs/REQUIREMENTS.md
  examples/bare-metal/sample-ansible-vars.yaml
  examples/vsphere/sample-terraform-dhcp.tfvars
  examples/vsphere/sample-terraform-minimal.tfvars
  examples/vsphere/sample-terraform-static-ips.tfvars
  examples/vsphere/sample-terraform-static-singlestore.tfvars
  examples/vsphere/sample-terraform-vi.tfvars
  main.tf
  requirements.txt
  roles/kubernetes/common/defaults/main.yaml
  roles/kubernetes/cri/containerd/defaults/main.yaml
  roles/kubernetes/cri/containerd/tasks/main.yaml
  templates/ansible/ansible-vars.yaml.tmpl
  variables.tf
Labels: documentation, enhancement
